export const ON_PHOTOS_REQUEST = 'ON_PHOTOS_REQUEST'
export const ON_PHOTOS_RECEIVED = 'ON_PHOTOS_RECEIVED'
export const ON_PHOTO_DETAIL_RECEIVED = 'ON_PHOTO_DETAIL_RECEIVED'
export const ON_CLOSE_PHOTO_DETAIL = 'ON_CLOSE_PHOTO_DETAIL'
